# Generated by Django 2.2.5 on 2019-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('product_name', models.CharField(max_length=50)),
                ('bought_by', models.CharField(max_length=50)),
                ('product_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
